### PR TITLE
When not implemented xref-* should not raise an error on the Emacs side

### PR DESCRIPTION
**Pull request by PuercoPop**
Btw, feel free to not use the commit itself as I did not used the async idioms used through the code, although AFAIU they are only needed when communicating with the lisp side.

### CODE REVIEW

**Comment by capitaomorte** [comment]
Had never looked in that part to be honest: doesn't it make more sense to check if they're implemented on the emacs-lisp *before* actually sending the slynk request? That way you would only have to move that sexp and it could still raise the error, which is normally displayed in the echo area. WDYT?

**Comment by PuercoPop** [comment]
Checking on the emacs lisp side before sending the request would imply that emacs keep a table of supported features per implementation? If so I would be against it. I like the fact that sly uses runtime introspection. The other way would be to query at startup the supported features?

**Comment by capitaomorte** [comment]
Hmm, you may well be right, I probably misread the problem completely. I'll have a better look tomorrow...

**Comment by PuercoPop** [comment]
To be Illustrate the problem through an example. If I do C-c C-w C-s (sly-xref-who-sets) on sbcl I get an emacs backtrace saying operation not support. With this patch I get a message on the echo area saying who-sets is not implemented on sbcl.

**Comment by capitaomorte** [comment]
@PuercoPop, yes in the meantime I understood that that is what is happening. But you only get that backtrace because you have `debug-on-error`, an Emacs variable, set to `t`. You should indeed have this variable set to T when developing emacs-lisp code, but generally not when using Emacs. I personally think it's bad practice to mask errors and second-guess an Emacs developer's preferences for having his `debug-on-error` set to t.

But I would accept a patch that makes the error message nicer on the command line for all `sly-eval-async` calls. So a silly program like this:
```elisp
(sly-eval-async
    `(cl:+ 1 2)
  (lambda (result)
    (concat "thingy" result)))
```
which currently prints a misterious

```
error in process filter: Wrong type argument: sequencep, 3
```

Could perhaps print

```
[sly] async callback errored: wrong type argument: sequencep, 3
```

But only if `debug-on-error` is set to nil. With it set to t, I do want to see the backtrace.

> The other way would be to query at startup the supported features?

This is another, independent improvement, but also interesting. I would also accept a patch that uses SLY's existing mechanism for this for bringing in information about xref capabilities, perhaps in `:features`, or maybe some other generic enough keyword you can come up with. Here's what my SBCL currently reports on the very first contact:

```
(:ok
  (:pid 78124 :style :spawn :encoding
        (:coding-systems
         ("utf-8-unix" "iso-latin-1-unix"))
        :lisp-implementation
        (:type "SBCL" :name "sbcl" :version "1.2.2" :program "/usr/local/Cellar/sbcl/1.2.2/bin/sbcl")
        :machine
        (:instance "king" :type "X86-64" :version "Intel(R) Core(TM)2 Duo CPU     E7600  @ 3.06GHz")
        :features
        (:slynk :quicklisp :asdf3 :asdf2 :asdf :os-unix :non-base-chars-exist-p :asdf-unicode :alien-callbacks :ansi-cl :ash-right-vops :bsd :c-stack-is-control-stack :common-lisp :compare-and-swap-vops :complex-float-vops :cycle-counter :darwin :darwin9-or-better :float-eql-vops ...)
        :modules
        ("SB-CLTL2" "SB-INTROSPECT" "SB-BSD-SOCKETS" "SB-POSIX" "ASDF")
        :package
        (:name "COMMON-LISP-USER" :prompt "CL-USER")
        :version "1.0.0-beta"))
```

**Comment by PuercoPop** [comment]
> But only if debug-on-error is set to nil. With it set to t, I do want to see the backtrace.

I disagree. IMHO a feature not implemented is not an error but a condition and a message notifying the user is what would be appropriate. So I wasn't try to mask an error but 'fixing' that it was treated as one. I thought it wouldn't be a controversial view but I appear to be mistaken.

**Comment by capitaomorte** [comment]
> IMHO a feature not implemented is not an error but a condition 

Well, you have point in this particular case: indeed a feature not implemented on the Slynk side is not an error of the user of the Emacs side per se, so I guess a `sly-warning` or `sly-message` is OK.

But generally, even very common stuff in SLY (and Emacs) like navigating past the available compiler notes in a button, is an error. And with `debug-on-error` you will get an emacs-lisp backtrace, which is quite useful, when you're debugging elisp but not when you're using SLY or Emacs for actual work.

If you don't mind my asking, why do you have `debug-on-error` set to `t` by default? You must get backtraces all the time, right? I only turn it off when I see an error message in the echo area.

**Comment by PuercoPop** [comment]
I was just talking about this particular case. Otherwise I agree with you that a backtrace is in order. That is why one sets debug-on-error

> If you don't mind my asking, why do you have debug-on-error set to t by default? You must get backtraces all the time, right?

When I started using emacs I got errors on init.el all the time, and the standard debugging MO was to start emacs with --debug-init. Also I wanted to be a good denizen of the FLOSS ecosystem so I figured it would allow me be proactive and fix the errors I encounter myself or at the very least give me a better mental model of whaat is happening so when I file the bug. So I just left it there.
 
I don't really get much backtraces these days. The only one is the elusive #34.

**Comment by capitaomorte** [comment]
> I don't really get much backtraces these days. The only one is the elusive #34.

Really? Then when you inadvertently `M-p` too much when checking out compiler notes? btw I have to look into that one #34, if indeed you still get it.

> Also I wanted to be a good denizen of the FLOSS ecosystem 

That's fantastic, but you could also do that and `M-x toggle-debug-on-error` selectively when emacs beeps and something looks fishy in the echo area. This is how I suppose this flag was thought.

Anyway, your use case seems reasonable enough, so I'm thinking of adding `sly-toggle-debug-on-async-error` which goes along nicely with the existing `sly-toggle-debug-on-slynk-error`. What do you think? It prints a nice 
```
[sly] `sly-eval-async' errored: who-sets is not implemented yet on sbcl.
```
Instead of the "error in process filter" that one never knows whence it came. It works just like `debug-on-error`

```diff
diff --git a/sly.el b/sly.el
index ca110cc..97d1810 100644
--- a/sly.el
+++ b/sly.el
@@ -2142,6 +2142,18 @@ or nil if nothing suitable can be found.")
              (error "Lisp connection closed unexpectedly"))
            (accept-process-output nil 0.01)))))))
 
+(defvar sly-debug-on-async-error nil
+  "If non-nil, enter debugger on errors of `sly-eval-async'.
+Specifically, this turns on debugging for errors popping up in
+emacs-lisp code handling the continuation. For debugging
+Slynk-side errors, see `sly-debug-on-slynk-error'")
+
+(defun sly-toggle-debug-on-async-error ()
+  (interactive)
+  (setq sly-debug-on-async-error (not sly-debug-on-async-error))
+  (sly-message "Debugging of `sly-eval-async' %s globally"
+               (if sly-debug-on-async-error "enabled" "disabled")))
+
 (defun sly-eval-async (sexp &optional cont package env)
   "Evaluate EXPR on the superior Lisp and call CONT with the result.
 
@@ -2154,7 +2166,17 @@ alist of bindings"
      (when cont
        (set-buffer buffer)
        (cl-progv (mapcar #'car env) (mapcar #'cdr env)
-         (funcall cont result))))
+         (if sly-debug-on-async-error
+             (let ((debug-on-error t))
+               (funcall cont result))
+           (condition-case err
+               (funcall cont result)
+             (error
+              (sly-message "`sly-eval-async' errored: %s"
+                           (if (and (eq 'error (car err))
+                                    (stringp (cadr err)))
+                               (cadr err)
+                             err))))))))
     ((:abort condition)
      (sly-message "Evaluation aborted on %s." condition)))
   ;; Guard against arbitrary return values which once upon a time
```

**Comment by PuercoPop** [comment]
Well I maintain that the case is not an error and that otherwise errors should raise the backtrace according to debug on error. But if you feel otherwise I think the best course of action would be to leave sly unchanged.

When I move past compiler notes I get a message on the echo area. (Although compilation mode is a mode I'm pretty sure I have to read the manual as my interaction with it is pretty clunky)

#34 is weird on some commits I get it on other ones I can't seem to trigger it. Normally I trigger when on the closing parens.

Btw do you plan announcing the beta on reddit?

**Comment by capitaomorte** [comment]
> But if you feel otherwise I think the best course of action would be to leave sly unchanged.

the idea I proposed is good for other kinds of "error in process filter" messages that also bug me (and perhaps other users), even if I do have debug-on-error set to nil.

Regarding xref availability, the best course of action would be to do what you proposed, and query capabilities at sly startup.

> When I move past compiler notes I get a message on the echo area. (Although compilation mode

Makes sense if you move to them in the compilation-mode buffer. I meant in the lisp-mode buffer itself. You can also move through them there with `M-p` and `M-n`.

> Btw do you plan announcing the beta on reddit?

No, but I won't mind if you do :-) have you checked out the new features already?

**Comment by PuercoPop** [comment]
In general I think we should strive to reduce the side of the code base (and modularize it), the LoC vs Benefit ratio is not worth it imho.

> No, but I won't mind if you do :-)

Will do a little publicity never hurts.

> have you checked out the new features already?

I have had sly-stickers enabled for a while now and every now and then when the oportunity arose I tried to use it. But as I now see when reading the improved documentation I was misunderstanding it. I thought of it as a trace this variable so every time that I tried to arm a variable (not the form) it wouldn't stick.

**Comment by capitaomorte** [comment]
> In general I think we should strive to reduce the side of the code base (and modularize it), the LoC vs Benefit ratio is not worth it imho.

You're right. I commited a much simpler version. I also commited a reworked version of your second commit which I believe closes the issue

**Comment by PuercoPop** [comment]
I like it, :+1:

Btw I've written about Sly entering beta. here: https://www.reddit.com/r/lisp/comments/3iiym7/sly_enters_beta/

I did my best to sum up the most salient features from the user perspective. Went thin on the details for the elisp side rewrite. as I don't recall them exactly. I remember reading that Slime implemented widgets/buttons provided by emacs due to predating it but as I was not sure I preferred to omit that. Better safe than sorry.

**Comment by capitaomorte** [comment]
Thank you Javier, I read it and it's fine, just your views on the subject. I wasn't expecting it so early, I'm going on vacation without a laptop so won't have time to deal promptly with any issues.

**Comment by PuercoPop** [comment]
Remember to forget your phone as well. Have fun!

**Pull request closed without merging**
