### PR TITLE
Exclude apparently uninterned symbols from completions

### PR DESCRIPTION
**Pull request by PuercoPop**

### CODE REVIEW

**Comment by PuercoPop** [comment]
Apparently the destructuring bind of the *with* clause loop is handled breaks on CCL. `(loop with (a b) := (nil) ..)` raises an error on CCL. This happens when `qualified-matching` does not find any matches. For example when trying to match `:fo<tab>`

This is an issue with the previous version as well.

**Comment by capitaomorte** [comment]
> Apparently the destructuring bind of the with clause loop is handled breaks on CCL. (loop with (a b) := (nil) ..)

Can't reproduce this on a recent CCL. Are you sure that's the problem?

**Comment by capitaomorte** [comment]
Fixed this in 4a0a8268948d3a569bcbb774824b7c4c203350f2

**Comment by PuercoPop** [comment]
> Can't reproduce this on a recent CCL. Are you sure that's the problem?

I am, it is a bug in CCL. It was present in the years old CCL version I had installed and also when I updated CCL, current version `"Version 1.12-dev-r16660  (LinuxX8664)"`

This is the [snippet](http://paste.lisp.org/display/314678) of the reduced test case. However for slynk code to trigger the bug, qualified-matching has to return nil, which is impossible as it is.

**Pull request closed without merging**
