### PR TITLE
Disable `view-read-only` for popup buffers.

### PR DESCRIPTION
**Pull request by ruricolist**
This binds `view-read-only` to `nil` around pop-up buffers so they don't open in View mode, which generally interferes with their key bindings.

### CODE REVIEW

**Comment by capitaomorte** [comment]
Hi @ruricolist and sorry for the long delay. I was just taking a look at this, and can't reproduce the initial situation, i.e. my pop-up buffers such as `*sly-db*` and `*sly-inspector*` don't open in view mode.

**Comment by ruricolist** [comment]
Do you have `view-read-only` set or customized to T?

**Comment by capitaomorte** [comment]
@ruricolist I think I understand what you mean now, sorry if I was being dumb. You mean bind it to `nil` in `sly-with-popup-buffer` so that even if the user has it customized to `t` no interference happens, right?

**Comment by capitaomorte** [comment]
This makes sense. I closed this using a cherry-picked version of your pull request. Used cherry-pick so I could edit the message according to the [convention](https://github.com/capitaomorte/sly/blob/master/CONTRIBUTING.md#commit-messages) (have a look, but don't let this disencourage you from contributing).

**Pull request closed without merging**
